services:
  mysql:
    image: mysql:8.1
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - /home/kuhlen/ootp/sql_files:/sql_files
      - /home/kuhlen/ootp/config/my.cnf:/etc/mysql/my.cnf
    networks:
      - ootp_network

  bot:
    build:
      context: .
    container_name: discord_bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mysql
    volumes:
      - /home/kuhlen/ootp/sql_files:/sql_files
    environment:
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      DISCORD_TOKEN: ${TOKEN}
      CLIENTID: ${CLIENTID}
      GUILDID: ${GUILDID}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - ootp_network

volumes:
  mysql_data:

networks:
  ootp_network:
    driver: bridge
