-- CreateTable
CREATE TABLE `divisions` (
    `league_id` INTEGER NOT NULL,
    `sub_league_id` INTEGER NOT NULL,
    `division_id` INTEGER NOT NULL,
    `name` VARCHAR(50) NULL,
    `gender` INTEGER NULL,

    PRIMARY KEY (`league_id`, `sub_league_id`, `division_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `games` (
    `game_id` INTEGER NOT NULL,
    `league_id` INTEGER NULL,
    `home_team` INTEGER NULL,
    `away_team` INTEGER NULL,
    `attendance` INTEGER NULL,
    `date` DATE NULL,
    `time` SMALLINT NULL,
    `game_type` SMALLINT NULL,
    `played` TINYINT NULL,
    `innings` SMALLINT NULL,
    `runs0` SMALLINT NULL,
    `runs1` SMALLINT NULL,
    `hits0` SMALLINT NULL,
    `hits1` SMALLINT NULL,
    `errors0` SMALLINT NULL,
    `errors1` SMALLINT NULL,
    `winning_pitcher` INTEGER NULL,
    `losing_pitcher` INTEGER NULL,
    `save_pitcher` INTEGER NULL,
    `starter0` INTEGER NULL,
    `starter1` INTEGER NULL,

    PRIMARY KEY (`game_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `leagues` (
    `league_id` INTEGER NOT NULL,
    `name` VARCHAR(50) NULL,
    `abbr` VARCHAR(50) NULL,
    `nation_id` INTEGER NULL,
    `language_id` INTEGER NULL,
    `gender` INTEGER NULL,
    `historical_league` TINYINT NULL,
    `logo_file_name` VARCHAR(200) NULL,
    `players_path` VARCHAR(200) NULL,
    `start_date` DATE NULL,
    `preferred_start_date` DATE NULL,
    `pitcher_award_name` VARCHAR(50) NULL,
    `mvp_award_name` VARCHAR(50) NULL,
    `rookie_award_name` VARCHAR(50) NULL,
    `defense_award_name` VARCHAR(50) NULL,
    `fictional_players` TINYINT NULL,
    `start_fantasy_draft` TINYINT NULL,
    `trading_deadline` TINYINT NULL,
    `winter_meetings` TINYINT NULL,
    `arbitration_offering` TINYINT NULL,
    `show_draft_pool` TINYINT NULL,
    `rosters_expanded` TINYINT NULL,
    `draft_date` DATE NULL,
    `rule_5_draft_date` DATE NULL,
    `international_fa_date` DATE NULL,
    `roster_expand_date` DATE NULL,
    `trade_deadline_date` DATE NULL,
    `allstar_date` DATE NULL,
    `days_until_deadline` INTEGER NULL,
    `next_draft_type` INTEGER NULL,
    `parent_league_id` INTEGER NULL,
    `league_state` SMALLINT NULL,
    `season_year` INTEGER NULL,
    `historical_year` SMALLINT NULL,
    `league_level` SMALLINT NULL,
    `stats_detail` INTEGER NULL,
    `historical_import_path` VARCHAR(200) NULL,
    `foreigner_percentage` SMALLINT NULL,
    `was_ootp6` TINYINT NULL,
    `was_65` TINYINT NULL,
    `allstar_game` TINYINT NULL,
    `auto_schedule_allstar` TINYINT NULL,
    `allstar_team_id0` INTEGER NULL,
    `allstar_team_id1` INTEGER NULL,
    `schedule_file_1` VARCHAR(200) NULL,
    `schedule_file_2` VARCHAR(200) NULL,
    `rules_rule_5` TINYINT NULL,
    `rules_minor_league_options` TINYINT NULL,
    `rules_trading` TINYINT NULL,
    `rules_trading_deadline_events` SMALLINT NULL,
    `rules_draft_pick_trading` TINYINT NULL,
    `rules_financials` TINYINT NULL,
    `rules_amateur_draft` TINYINT NULL,
    `rules_fa_compensation` SMALLINT NULL,
    `rules_schedule_balanced` TINYINT NULL,
    `rules_schedule_inter_league` TINYINT NULL,
    `rules_schedule_force_start_day` TINYINT NULL,
    `rules_trades_other_leagues` TINYINT NULL,
    `rules_free_agents_from_other_leagues` TINYINT NULL,
    `rules_free_agents_leave_other_leagues` TINYINT NULL,
    `rules_allstar_game` TINYINT NULL,
    `rules_spring_training` TINYINT NULL,
    `rules_active_roster_limit` SMALLINT NULL,
    `rules_secondary_roster_limit` SMALLINT NULL,
    `rules_expanded_roster_limit` SMALLINT NULL,
    `rules_min_service_days` SMALLINT NULL,
    `rules_waiver_period_length` SMALLINT NULL,
    `rules_dfa_period_length` SMALLINT NULL,
    `rules_fa_minimum_years` SMALLINT NULL,
    `rules_salary_arbitration_minimum_years` SMALLINT NULL,
    `rules_minor_league_fa_minimum_years` SMALLINT NULL,
    `rules_foreigner_limit` SMALLINT NULL,
    `rules_foreigner_pitcher_limit` SMALLINT NULL,
    `rules_foreigner_hitter_limit` SMALLINT NULL,
    `rules_schedule_games_per_team` SMALLINT NULL,
    `rules_schedule_typical_series` SMALLINT NULL,
    `rules_schedule_game_times` SMALLINT NULL,
    `rules_schedule_preferred_start_day` SMALLINT NULL,
    `rules_amateur_draft_rounds` SMALLINT NULL,
    `rules_minimum_salary` INTEGER NULL,
    `rules_salary_cap` INTEGER NULL,
    `rules_player_salary0` INTEGER NULL,
    `rules_player_salary1` INTEGER NULL,
    `rules_player_salary2` INTEGER NULL,
    `rules_player_salary3` INTEGER NULL,
    `rules_player_salary4` INTEGER NULL,
    `rules_player_salary5` INTEGER NULL,
    `rules_player_salary6` INTEGER NULL,
    `rules_player_salary7` INTEGER NULL,
    `rules_average_coach_salary` INTEGER NULL,
    `rules_average_attendance` INTEGER NULL,
    `rules_average_national_media_contract` INTEGER NULL,
    `rules_cash_maximum` INTEGER NULL,
    `rules_average_ticket_price` DOUBLE NULL,
    `rules_luxury_sharing` TINYINT NULL,
    `rules_revenue_sharing` TINYINT NULL,
    `rules_revenue_sharing_tax` SMALLINT NULL,
    `rules_luxury_sharing_cap` SMALLINT NULL,
    `rules_luxury_tax` SMALLINT NULL,
    `rules_national_media_contract_fixed` TINYINT NULL,
    `rules_owner_decides_budget` TINYINT NULL,
    `rules_schedule_auto_adjust_dates` TINYINT NULL,
    `rules_historical_import_rookies` TINYINT NULL,
    `avg_rating_contact` INTEGER NULL,
    `avg_rating_gap` INTEGER NULL,
    `avg_rating_power` INTEGER NULL,
    `avg_rating_eye` INTEGER NULL,
    `avg_rating_strikeouts` INTEGER NULL,
    `avg_rating_stuff` INTEGER NULL,
    `avg_rating_movement` INTEGER NULL,
    `avg_rating_control` INTEGER NULL,
    `avg_rating_fielding0` INTEGER NULL,
    `avg_rating_fielding1` INTEGER NULL,
    `avg_rating_fielding2` INTEGER NULL,
    `avg_rating_fielding3` INTEGER NULL,
    `avg_rating_fielding4` INTEGER NULL,
    `avg_rating_fielding5` INTEGER NULL,
    `avg_rating_fielding6` INTEGER NULL,
    `avg_rating_fielding7` INTEGER NULL,
    `avg_rating_fielding8` INTEGER NULL,
    `avg_rating_fielding9` INTEGER NULL,
    `avg_rating_overall` INTEGER NULL,
    `avg_rating_age` DOUBLE NULL,
    `league_totals_ab` INTEGER NULL,
    `league_totals_h` INTEGER NULL,
    `league_totals_d` INTEGER NULL,
    `league_totals_t` INTEGER NULL,
    `league_totals_hr` INTEGER NULL,
    `league_totals_bb` INTEGER NULL,
    `league_totals_hp` INTEGER NULL,
    `league_totals_k` INTEGER NULL,
    `league_totals_pa` INTEGER NULL,
    `league_totals_babip` DOUBLE NULL,
    `league_totals_mod_h` DOUBLE NULL,
    `league_totals_mod_d` DOUBLE NULL,
    `league_totals_mod_t` DOUBLE NULL,
    `league_totals_mod_hr` DOUBLE NULL,
    `league_totals_mod_bb` DOUBLE NULL,
    `league_totals_mod_hp` DOUBLE NULL,
    `league_totals_mod_k` DOUBLE NULL,
    `league_totals_mod_babip` DOUBLE NULL,
    `ml_equivalencies_avg` DOUBLE NULL,
    `ml_equivalencies_hr` DOUBLE NULL,
    `ml_equivalencies_eb` DOUBLE NULL,
    `ml_equivalencies_bb` DOUBLE NULL,
    `ml_equivalencies_k` DOUBLE NULL,
    `ml_equivalencies_hp` DOUBLE NULL,
    `player_creation_modifier_contact` DOUBLE NULL,
    `player_creation_modifier_gap` DOUBLE NULL,
    `player_creation_modifier_power` DOUBLE NULL,
    `player_creation_modifier_eye` DOUBLE NULL,
    `player_creation_modifier_strikeouts` DOUBLE NULL,
    `player_creation_modifier_stuff` DOUBLE NULL,
    `player_creation_modifier_movement` DOUBLE NULL,
    `player_creation_modifier_control` DOUBLE NULL,
    `player_creation_modifier_speed` DOUBLE NULL,
    `player_creation_modifier_fielding` DOUBLE NULL,
    `financial_coefficient` DOUBLE NULL,
    `world_start_year` INTEGER NULL,
    `current_date` DATE NULL,
    `background_color_id` VARCHAR(8) NULL,
    `text_color_id` VARCHAR(8) NULL,
    `scouting_coach_id` INTEGER NULL,

    PRIMARY KEY (`league_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `messages` (
    `message_id` INTEGER NOT NULL,
    `subject` VARCHAR(255) NULL,
    `player_id_0` INTEGER NULL,
    `player_id_1` INTEGER NULL,
    `player_id_2` INTEGER NULL,
    `player_id_3` INTEGER NULL,
    `player_id_4` INTEGER NULL,
    `player_id_5` INTEGER NULL,
    `player_id_6` INTEGER NULL,
    `player_id_7` INTEGER NULL,
    `player_id_8` INTEGER NULL,
    `player_id_9` INTEGER NULL,
    `team_id_0` INTEGER NULL,
    `team_id_1` INTEGER NULL,
    `team_id_2` INTEGER NULL,
    `team_id_3` INTEGER NULL,
    `team_id_4` INTEGER NULL,
    `league_id_0` INTEGER NULL,
    `league_id_1` INTEGER NULL,
    `importance` INTEGER NULL,
    `message_type` INTEGER NULL,
    `hype` SMALLINT NULL,
    `sender_type` INTEGER NULL,
    `sender_id` INTEGER NULL,
    `recipient_id` INTEGER NULL,
    `trade_id` INTEGER NULL,
    `date` DATE NULL,
    `deleted` TINYINT NULL,
    `notify` TINYINT NULL,
    `ongoing_story_id` INTEGER NULL,
    `text_is_modified` TINYINT NULL,

    PRIMARY KEY (`message_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `players` (
    `player_id` INTEGER NOT NULL,
    `team_id` INTEGER NULL,
    `league_id` INTEGER NULL,
    `position` SMALLINT NULL,
    `role` SMALLINT NULL,
    `first_name` VARCHAR(50) NULL,
    `last_name` VARCHAR(50) NULL,
    `nick_name` VARCHAR(50) NULL,
    `age` SMALLINT NULL,
    `date_of_birth` DATE NULL,
    `city_of_birth_id` INTEGER NULL,
    `nation_id` INTEGER NULL,
    `second_nation_id` INTEGER NULL,
    `weight` SMALLINT NULL,
    `height` SMALLINT NULL,
    `retired` TINYINT NULL,
    `free_agent` TINYINT NULL,
    `last_league_id` INTEGER NULL,
    `last_team_id` INTEGER NULL,
    `organization_id` INTEGER NULL,
    `last_organization_id` INTEGER NULL,
    `language_ids0` INTEGER NULL,
    `language_ids1` INTEGER NULL,
    `uniform_number` SMALLINT NULL,
    `experience` SMALLINT NULL,
    `person_type` SMALLINT NULL,
    `bats` SMALLINT NULL,
    `throws` SMALLINT NULL,
    `personality_greed` SMALLINT NULL,
    `personality_loyalty` SMALLINT NULL,
    `personality_play_for_winner` SMALLINT NULL,
    `personality_work_ethic` SMALLINT NULL,
    `personality_intelligence` SMALLINT NULL,
    `personality_leader` SMALLINT NULL,
    `historical_id` VARCHAR(50) NULL,
    `historical_team_id` VARCHAR(50) NULL,
    `best_contract_offer_id` INTEGER NULL,
    `injury_is_injured` TINYINT NULL,
    `injury_dtd_injury` TINYINT NULL,
    `injury_career_ending` TINYINT NULL,
    `injury_dl_left` SMALLINT NULL,
    `injury_dl_playoff_round` SMALLINT NULL,
    `injury_left` SMALLINT NULL,
    `dtd_injury_effect` SMALLINT NULL,
    `dtd_injury_effect_hit` SMALLINT NULL,
    `dtd_injury_effect_throw` SMALLINT NULL,
    `dtd_injury_effect_run` SMALLINT NULL,
    `injury_id` SMALLINT NULL,
    `injury_id2` SMALLINT NULL,
    `injury_dtd_injury2` TINYINT NULL,
    `injury_left2` SMALLINT NULL,
    `dtd_injury_effect2` SMALLINT NULL,
    `dtd_injury_effect_hit2` SMALLINT NULL,
    `dtd_injury_effect_throw2` SMALLINT NULL,
    `dtd_injury_effect_run2` SMALLINT NULL,
    `prone_overall` SMALLINT NULL,
    `prone_leg` SMALLINT NULL,
    `prone_back` SMALLINT NULL,
    `prone_arm` SMALLINT NULL,
    `fatigue_pitches0` SMALLINT NULL,
    `fatigue_pitches1` SMALLINT NULL,
    `fatigue_pitches2` SMALLINT NULL,
    `fatigue_pitches3` SMALLINT NULL,
    `fatigue_pitches4` SMALLINT NULL,
    `fatigue_pitches5` SMALLINT NULL,
    `fatigue_points` SMALLINT NULL,
    `fatigue_played_today` TINYINT NULL,
    `running_ratings_speed` SMALLINT NULL,
    `running_ratings_stealing` SMALLINT NULL,
    `running_ratings_baserunning` SMALLINT NULL,
    `college` TINYINT NULL,
    `acquired` SMALLINT NULL,
    `acquired_date` DATE NULL,
    `draft_year` SMALLINT NULL,
    `draft_round` SMALLINT NULL,
    `draft_supplemental` TINYINT NULL,
    `draft_pick` SMALLINT NULL,
    `draft_overall_pick` SMALLINT NULL,
    `draft_eligible` TINYINT NULL,
    `hsc_status` SMALLINT NULL,
    `redshirt` TINYINT NULL,
    `picked_in_draft` TINYINT NULL,
    `school` SMALLINT NULL,
    `commit_school` SMALLINT NULL,
    `hidden` TINYINT NULL,
    `draft_league_id` INTEGER NULL,
    `draft_team_id` INTEGER NULL,
    `turned_coach` TINYINT NULL,
    `hall_of_fame` TINYINT NULL,
    `rust` SMALLINT NULL,
    `inducted` SMALLINT NULL,
    `strategy_override_team` TINYINT NULL,
    `strategy_stealing` INTEGER NULL,
    `strategy_running` INTEGER NULL,
    `strategy_bunt_for_hit` INTEGER NULL,
    `strategy_sac_bunt` INTEGER NULL,
    `strategy_hit_run` INTEGER NULL,
    `strategy_hook_start` INTEGER NULL,
    `strategy_hook_relief` INTEGER NULL,
    `strategy_pitch_count` INTEGER NULL,
    `strategy_pitch_around` INTEGER NULL,
    `strategy_never_pinch_hit` TINYINT NULL,
    `strategy_defensive_sub` TINYINT NULL,
    `strategy_dtd_sit_min` TINYINT NULL,
    `strategy_dtd_allow_ph` TINYINT NULL,
    `local_pop` SMALLINT NULL,
    `national_pop` SMALLINT NULL,
    `draft_protected` TINYINT NULL,
    `morale` SMALLINT NULL,
    `morale_player_performance` SMALLINT NULL,
    `morale_team_performance` SMALLINT NULL,
    `morale_team_transactions` SMALLINT NULL,
    `expectation` SMALLINT NULL,
    `morale_player_role` SMALLINT NULL,
    `on_loan` TINYINT NULL,
    `loan_league_id` INTEGER NULL,
    `loan_team_id` INTEGER NULL,

    PRIMARY KEY (`player_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `team_record` (
    `team_id` INTEGER NOT NULL,
    `g` SMALLINT NULL,
    `w` SMALLINT NULL,
    `l` SMALLINT NULL,
    `t` SMALLINT NULL,
    `pos` SMALLINT NULL,
    `pct` DOUBLE NULL,
    `gb` DOUBLE NULL,
    `streak` SMALLINT NULL,
    `magic_number` SMALLINT NULL,

    PRIMARY KEY (`team_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `teams` (
    `team_id` INTEGER NOT NULL,
    `name` VARCHAR(50) NULL,
    `abbr` VARCHAR(50) NULL,
    `nickname` VARCHAR(50) NULL,
    `logo_file_name` VARCHAR(200) NULL,
    `city_id` INTEGER NULL,
    `park_id` INTEGER NULL,
    `league_id` INTEGER NULL,
    `sub_league_id` INTEGER NULL,
    `division_id` INTEGER NULL,
    `nation_id` INTEGER NULL,
    `parent_team_id` INTEGER NULL,
    `level` INTEGER NULL,
    `prevent_any_moves` TINYINT NULL,
    `human_team` TINYINT NULL,
    `human_id` INTEGER NULL,
    `gender` INTEGER NULL,
    `background_color_id` VARCHAR(8) NULL,
    `text_color_id` VARCHAR(8) NULL,
    `ballcaps_main_color_id` VARCHAR(8) NULL,
    `ballcaps_visor_color_id` VARCHAR(8) NULL,
    `jersey_main_color_id` VARCHAR(8) NULL,
    `jersey_away_color_id` VARCHAR(8) NULL,
    `jersey_secondary_color_id` VARCHAR(8) NULL,
    `jersey_pin_stripes_color_id` VARCHAR(8) NULL,
    `allstar_team` TINYINT NULL,
    `historical_id` VARCHAR(50) NULL,

    PRIMARY KEY (`team_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

